# PostgreSQL
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5433/winwintravel}
spring.datasource.username=${POSTGRES_USER:root}
spring.datasource.password=${POSTGRES_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=${JWT_SECRET:some_test_secret_api_12345678_text_klisch_secret}
jwt.expiration=3000000000

# Internal token / Data API
internal.token=${INTERNAL_TOKEN:jhasgfjksgfjkas___HKGJGHJKjsfglhHIG$^^FGVLKMNKL++++}
data-api.url=${DATA_API_URL:http://localhost:8081}

# Server
server.servlet.context-path=/api
server.port=8080